#ifndef RT_CONFIG_HEADER
#define RT_CONFIG_HEADER

#include "basic.h"


// buffer
static const u32 BUFFER_RESOLUTION_WIDTH = 1920;
static const u32 BUFFER_RESOLUTION_HEIGHT = 1080;
static const u32 BUFFER_RESOLUTION_PIXELS = BUFFER_RESOLUTION_WIDTH*BUFFER_RESOLUTION_HEIGHT;
static const s32 BUFFER_RESOLUTION_HWIDTH = BUFFER_RESOLUTION_WIDTH>>1;
static const s32 BUFFER_RESOLUTION_HHEIGHT = BUFFER_RESOLUTION_HEIGHT>>1;

// camera
static const f32 PERSPECTIVE_CLIPPING_FOV = 90.f;
static const f32 PERSPECTIVE_CLIPPING_NEAR = .1f;
static const f32 PERSPECTIVE_CLIPPING_FAR = 1000.f;

// graphics
static const f32 GFX_BACKGROUND_COLOUR_R = .0f;
static const f32 GFX_BACKGROUND_COLOUR_G = .0f;
static const f32 GFX_BACKGROUND_COLOUR_B = .0f;


#endif
